import { Toaster } from "@/components/ui/toaster";
import { ReactQueryClientProvider } from "@/utils/providers/ReactQueryProvider";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>
          <Toaster />
          <main>{children}</main>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
